/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f3faff',
        'surface-dim': '#c7dde9',
        'surface-bright': '#f3faff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#e6f6ff',
        'surface-container': '#dbf1fe',
        'surface-container-high': '#d5ecf8',
        'surface-container-highest': '#cfe6f2',
        'on-surface': '#071e27',
        'on-surface-variant': '#41493e',
        'inverse-surface': '#1e333c',
        'inverse-on-surface': '#dff4ff',
        outline: '#717a6d',
        'outline-variant': '#c0c9bb',
        'surface-tint': '#2a6b2c',
        primary: '#00450d',
        'on-primary': '#ffffff',
        'primary-container': '#1b5e20',
        'on-primary-container': '#90d689',
        secondary: '#00629e',
        'on-secondary': '#ffffff',
        'secondary-container': '#62b4fe',
        'on-secondary-container': '#004470',
        tertiary: '#00450d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#055f18',
        'on-tertiary-container': '#86d881',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#acf4a4',
        'primary-fixed-dim': '#91d78a',
        'on-primary-fixed': '#002203',
        'on-primary-fixed-variant': '#0c5216',
        'secondary-fixed': '#cfe5ff',
        'secondary-fixed-dim': '#99cbff',
        'on-secondary-fixed': '#001d34',
        'on-secondary-fixed-variant': '#004a78',
        'tertiary-fixed': '#a3f69c',
        'tertiary-fixed-dim': '#88d982',
        'on-tertiary-fixed': '#002204',
        'on-tertiary-fixed-variant': '#005312',
        background: '#f3faff',
        'on-background': '#071e27',
        'surface-variant': '#cfe6f2',
      },
      fontFamily: {
        hanken: ['Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      borderRadius: {
        xl: '0.75rem',
      },
      spacing: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}