services:

  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres

    environment:
      POSTGRES_USER: smartcity_user
      POSTGRES_PASSWORD: smartcity_pass
      POSTGRES_DB: smartcity

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped


  redis:
    image: redis:7
    container_name: redis

    command: redis-server --requirepass redispass

    ports:
      - "6379:6379"

    restart: unless-stopped


  chromadb:
    image: chromadb/chroma
    container_name: chromadb

    ports:
      - "8010:8000"

    restart: unless-stopped


volumes:
  postgres_data: